# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20180319_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
    ]
