# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20180318_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='category',
            new_name='categories',
        ),
    ]
