# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20180319_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441'),
            preserve_default=False,
        ),
    ]
