# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('name', 'created'), 'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441', 'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b'},
        ),
    ]
