# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20180322_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
