# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ('id', 'author'), 'verbose_name': '\u041b\u0430\u0439\u043a', 'verbose_name_plural': '\u041b\u0430\u0439\u043a\u0438'},
        ),
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='like',
            name='question',
        ),
        migrations.AddField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='contenttypes.ContentType', verbose_name='\u041f\u043e\u043d\u0440\u0430\u0432\u0438\u043b\u043e\u0441\u044c'),
        ),
        migrations.AddField(
            model_name='like',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
