# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_auto_20180406_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='contenttypes.ContentType', verbose_name='\u041f\u043e\u043d\u0440\u0430\u0432\u0438\u043b\u043e\u0441\u044c'),
        ),
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
